### ISSUE TITLE
cmake failed 

### ISSUE THREAD

**Issue by wuhongda** [Tencent/Tendis#54] opened 2021-01-12 05:46 UTC
CMake Error: install(EXPORT "glog-targets" ...) includes target "glog" which requires target "gflags_nothreads_static" that is not in the export set.
CMake Error: install(EXPORT "RocksDBTargets" ...) includes target "rocksdb" which requires target "gflags_nothreads_static" that is not in the export set.
CMake Error: install(EXPORT "RocksDBTargets" ...) includes target "rocksdb-shared" which requires target "gflags_nothreads_static" that is not in the export set.
-- Generating done

**Comment by TendisDev** [comment] 2021-01-14 03:16
Duplicate of #9

**Comment by TendisDev** [comment] 2021-03-16 05:29
已解决

**Closed** 2021-04-30 07:18 UTC
Labels: compile, duplicate, fixed
